### ISSUE TITLE
Final Cut Pro Menu Items Cache doesn't update when upgrading to 10.4.1

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1140]
After installing Final Cut Pro 10.4.1:

![screen shot 2018-04-10 at 7 52 53 am](https://user-images.githubusercontent.com/22286696/38525056-3bd589be-3c94-11e8-8d06-077a7d16db48.png)

However, if you trash your CommandPost Preferences, this fixes things.

**Comment by latenitefilms** [comment]
I feel like `plugins.finalcutpro.watchers.version` is probably supposed to handle this, but it currently doesn't. I'm not sure `plugins.finalcutpro.watchers.version` actually does anything currently?

**Comment by randomeizer** [comment]
It may not. You should be able to watch FCP.getVersion directly I think.

**Comment by latenitefilms** [comment]
@randomeizer - Has this been solved with `cp.app`?

**Comment by randomeizer** [comment]
Not sure. I didn't change anything specific regarding caching.


On 30 May 2018 at 11:49 pm, Chris Hocking <notifications@github.com> wrote:


@randomeizer <https://github.com/randomeizer> - Has this been solved with
cp.app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/1140#issuecomment-393168895>,
or mute the thread

**Comment by latenitefilms** [comment]
I'm going to close this issue for now then, and we can re-open if it becomes an issue.
