### ISSUE TITLE
Sean Landers Ideas for Final Cut Pro

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#124]
http://www.rednail.com.au/2016/12/making-final-cut-pro-great-again-for-pros/

**Comment by randomeizer** [comment]
Interesting list. Some are possible, some not so much, some I actually disagree with.

Going down the list:

* _Renaming Libraries/Events/Projects to Projects/Bins/Sequences_ - I disagree with this. I'm not in love with the label of 'Events', but having a nomenclature which is inconsistent between different users is just asking for trouble. Especially if you're redefining what a 'Project' is completely.  "I lost my project", "Your 'advanced' project, or 'beginner' project" "What? I mean my library." "Oh...". Honestly, people just need to move on from this issue.
* _Metadata ripple_ - I'd like to know what metadata he wants to ripple specifically. Earlier versions of FCPX used to work this way - you make a change in the timeline and it affects the original. This  had its own limitations, in that you would unexpectedly create side-effects in other projects/compound clips that share the same source material. Could be useful for some specific metadata though. I'd personally rather it was an explicit command that I triggered when I wanted to push metadata one way or the other, rather than keeping everything synced all the time.
* _Master sequence settings_ - This, we could probably implement. It would be a matter of watching for the 'New Project' window and select the appropriate settings. The main challenge would be creating the UI for where those master settings are configured. Maybe a webview.
* _Customised Workspaces_ - Not something we can really do beyond what FCPX currently allows, to be honest.
* _Customize/save browser views_ - This would be doable. Simplest UI would be to 'snapshot' a configuration via a command, and then trigger it again later somehow. Either a set of 'preset' commands ala the Effect/Title/etc you already have, or maybe via the HUD or something.
* _Monitor/Audio calibration_ - Would be nice, but a bit beyond us, I think.
* _Setting location of rendered data_ - Beyond us I think.
* _Proxy compression settings_ - Would also be nice, we can't do it.
* _Dupe detection in the timeline_ - Maybe. Determining the actual source of media doesn't seem possible directly in the timeline - it would require jumping back and forth to find the source media in the browser, and then you have to somehow compare the in and out point of the clips for any that appear twice. Not impossible, but the UI/mouse will be doing a bit crazy doing the analysis.
* _Viewers gain position bar_ - would be nice, don't think we can do it.
* _Viewers can show next/previous clip_ - I've been trying to think of some way of hacking around this with the current app. The best option I've come up with so far would be something like this:
    1. Start a 'grading session'
    2. While in Grading mode, we ensure that we are working inside a compound clip. If it's a project, we wrap the whole thing in a compound clip and open it up in the timeline.
    3. We enable the Event Viewer, and sync it to view the compound clip we're currently editing, at the frame prior to (or after, depending on the mode) the beginning of the current clip.
    
    This would be easier if you could view Projects in the Event Viewer. Not sure why Apple doesn't allow that exactly - it's kinda annoying.
* _Dynamic Trimming_ - I'm not sure exactly what is meant by this term.
* _Consolidate Media with handles_ - Yeah, that would be awesome. I feel like this is something that could be best done with an XML + external app at the present, but it's not impossible. Just basically like writing an app of it's own...
* _Customisable UI with multiple browsers_ - Don't really see the value myself, but either way, not possible for us to hack at this point.

Your thoughts @latenitefilms?

**Comment by latenitefilms** [comment]
Replies as follows:

> Renaming Libraries/Events/Projects to Projects/Bins/Sequences - I disagree with this. I'm not in love with the label of 'Events', but having a nomenclature which is inconsistent between different users is just asking for trouble. Especially if you're redefining what a 'Project' is completely. "I lost my project", "Your 'advanced' project, or 'beginner' project" "What? I mean my library." "Oh...". Honestly, people just need to move on from this issue.

Personally, I think Apple should just rename "Projects" to "Timelines" and be done with it. I have considered going through and doing this myself via plist values - there's just a LOT of them to change!

> Metadata ripple - I'd like to know what metadata he wants to ripple specifically. Earlier versions of FCPX used to work this way - you make a change in the timeline and it affects the original. This had its own limitations, in that you would unexpectedly create side-effects in other projects/compound clips that share the same source material. Could be useful for some specific metadata though. I'd personally rather it was an explicit command that I triggered when I wanted to push metadata one way or the other, rather than keeping everything synced all the time.

I agree that it would be great to have some way to exchange metadata between the timeline and library. I feel like this is something we could do via XML or the Pasteboard though, if we were actually trying to resolve a specific problem.

> Master sequence settings - This, we could probably implement. It would be a matter of watching for the 'New Project' window and select the appropriate settings.

Agreed - you might even be able to do it via plists, as all the default values are stored in the `FFSequenceSettings` key in the Preferences. The trick will be whether or not Final Cut Pro is reading these values before opening the window or not.

> The main challenge would be creating the UI for where those master settings are configured. Maybe a webview.

I did some experiments early on with messing with the Preferences panels - and it is actually possible to mess around with them by modifying the appropriate `.nib` files. What we could do is take over the hidden "debug" preferences panel and make that a "Hacks" panel. Would require a lot of trial and error - but could be a fun little side project.

> Customised Workspaces - Not something we can really do beyond what FCPX currently allows, to be honest.

That's not entirely true - as the `.moduleLayout` files are just plain-text plists, so we can mess with them. The tricky thing with this, is you need to get everything right, or else Final Cut Pro will just crash. As discussed elsewhere, in the 10.2.3 Final Cut Pro bundle, there's actually a commented out "Actions History" in the main module - but I've never got it to actually work. Either way, with some more testing and experimenting, we might be able to do some cool things in this area.

> Customize/save browser views - This would be doable. Simplest UI would be to 'snapshot' a configuration via a command, and then trigger it again later somehow. Either a set of 'preset' commands ala the Effect/Title/etc you already have, or maybe via the HUD or something.

What I would personally LOVE to see is if each event/keyword/smart collection remembered it's view settings! For example, maybe I always want my music keyword collection to be in List view, but my selects to be in Filmstrip view. This is obviously slightly more tricky to implement, but not impossible.

However, the ability to save browser "presets" would also be pretty cool.

> Monitor/Audio calibration - Would be nice, but a bit beyond us, I think.

I think this could be fairly easy to implement - but yeah, not a priority.

> Setting location of rendered data - Beyond us I think.

I think this is technically possible using symbolic links - but low priority.

> Proxy compression settings - Would also be nice, we can't do it.

This is something I've been WANTING to do from day one. I'm sure there MUST be something in the Final Cut Pro bundle that will allow us to do this, but I haven't found the secret sauce yet. One day...

> Dupe detection in the timeline - Maybe. Determining the actual source of media doesn't seem possible directly in the timeline - it would require jumping back and forth to find the source media in the browser, and then you have to somehow compare the in and out point of the clips for any that appear twice. Not impossible, but the UI/mouse will be doing a bit crazy doing the analysis.

I think the best possible way we could do this is:

- Select All
- Copy the entire timeline to clipboard
- Analyse the clipboard contents for duplicates. If duplicates are found, put a generator on top.
- Go back to Final Cut Pro
- Paste over the existing timeline

> Viewers gain position bar - would be nice, don't think we can do it.

Ummm... I wonder if we could somehow use the mini-timeline from the Touch Bar for this?

> Viewers can show next/previous clip - I've been trying to think of some way of hacking around this with the current app. The best option I've come up with so far would be something like this:
> 
> - Start a 'grading session'
> - While in Grading mode, we ensure that we are working inside a compound clip. If it's a project, we wrap the whole thing in a compound clip and open it up in the timeline.
> - We enable the Event Viewer, and sync it to view the compound clip we're currently editing, at the frame prior to (or after, depending on the mode) the beginning of the current clip.
> - This would be easier if you could view Projects in the Event Viewer. Not sure why Apple doesn't allow that exactly - it's kinda annoying.

Sounds cool!

> Dynamic Trimming - I'm not sure exactly what is meant by this term.

https://helpx.adobe.com/premiere-pro/atv/cs6-tutorials/dynamic-trimming-and-editing-with-the-keyboard.html

> Consolidate Media with handles - Yeah, that would be awesome. I feel like this is something that could be best done with an XML + external app at the present, but it's not impossible. Just basically like writing an app of it's own...

Yeah, what I would EVENTUALLY love to do is basically build a Hammerspoon library/module for reading and processing both FCPXML and Final Cut Pro Pasteboard XML. Obviously this is REALLY hard to do - and [Intelligent Assistance](http://www.intelligentassistance.com) have spent years perfecting the way they handle and process FCPXML, but AFAIK there's currently no good open source solution to this problem, so I feel like this would be an awesome gap to fill.

> Customisable UI with multiple browsers - Don't really see the value myself, but either way, not possible for us to hack at this point.

This MIGHT be possible by messing with `.moduleLayout` files, but who knows what happens when you have two browsers - it might just crash.
