### ISSUE TITLE
Unable to find a menu matching '<function 1>'

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1245]
@randomeizer - FYI - I'm seeing a lot of these errors in the Error Log after your recent changes:

```
2018-05-28 00:09:48: 00:09:48 ** Warning:      menu: Unable to find a menu matching '<function 1>' (cp.i18n.localeID: English [en]) in cp.i18n.localeID: English [en]
```

**Comment by randomeizer** [comment]
Any particular actions triggering it?


On 28 May 2018 at 12:21 am, Chris Hocking <notifications@github.com> wrote:


@randomeizer <https://github.com/randomeizer> - FYI - I'm seeing a lot of
these errors in the Error Log after your recent changes:

2018-05-28 00:09:48: 00:09:48 ** Warning:      menu: Unable to find a
menu matching '<function 1>' (cp.i18n.localeID: English [en]) in
cp.i18n.localeID: English [en]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/1245>, or mute the thread

**Comment by latenitefilms** [comment]
I THINK it was mainly caused by the Batch Export tool.
