### ISSUE TITLE
Add hs._asm.axuielement:isValid()

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#1365]

**Comment by randomeizer** [comment]
Just had a look at the Apple API. Perhaps the `AXUIElementGetPid` function would be slightly  more reliable/better performance than copying a specific string value which may or may not exist in some cases?

**Comment by latenitefilms** [comment]
@randomeizer - Could you not just use `hs._asm.axuielement:pid()` for this then?

**Comment by randomeizer** [comment]
It would be better to check the error code, which isn't available in lua
land.


On 11 Jul 2018 at 7:41 am, Chris Hocking <notifications@github.com> wrote:


@randomeizer <https://github.com/randomeizer> - Could you not just use
hs._asm.axuielement:pid() for this then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/1365#issuecomment-403975217>,
or mute the thread

**Comment by randomeizer** [comment]
On that topic, it looks like most errors are getting "logged", but not
returned to the lua code. It means we can't detect when something breaks in
code - we can only check logs manually, and some of those don't seem to get
output. I'm guessing that the menu issues we've been having would have an
error code returned that isn't making it out to us.


On 11 Jul 2018 at 10:45 am, David Peterson <david@randombits.org> wrote:


It would be better to check the error code, which isn't available in lua
land.



On 11 Jul 2018 at 7:41 am, Chris Hocking <notifications@github.com> wrote:


@randomeizer <https://github.com/randomeizer> - Could you not just use
hs._asm.axuielement:pid() for this then?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/1365#issuecomment-403975217>,
or mute the thread
