### ISSUE TITLE
Use Github Releases API to automatically update 

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#162]
It would be handy to be able to auto-update FCPX Hacks when we do a new release.

https://developer.github.com/v3/repos/releases/

**Comment by latenitefilms** [comment]
This is definitely possible. I had previously considered just changing the update link to a direct link to the latest DMG on GitHub, but decided against it because I kinda liked that users had to go to the blog entry to download, as then they can also see what new features are there, etc.

Ages ago, I also looked into using https://sparkle-project.org to handle updates (as this is what Hammerspoon uses), but it became too hard because once we turn FCPX Hacks into a "proper" Application, then we have to deal with App-Signing.

So maybe we just write a LUA-based clone of Sparkle, so it has the same look (i.e. has release notes, option to allow automatic downloads in future, etc.)?
 
<img width="620" alt="screenshot-noshadow 2x" src="https://cloud.githubusercontent.com/assets/22286696/21597499/ca868b74-d19f-11e6-8540-ce04efa7d23b.png">

**Comment by randomeizer** [comment]
Sure, depends how complicated you want to get. I'm not sure exactly how
fancy we can make the dialogue box - although I guess we can use a webview?

**Comment by latenitefilms** [comment]
I think making a dialog box like that is beyond the scope of AppleScript, so yeah, we'd either have to use a `hs.webview`, or we could build the dialog in Xcode (using AppleScriptObjC), then control it via LUA.

I think something like the Sparkle dialog would be great if we can pull it off.
