### ISSUE TITLE
Command Set resets to 'Default' after upgrading

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#174]
Wouldn't it be better to keep the user's custom configuration?

**Comment by latenitefilms** [comment]
Yes, but the reason for this is that because an update might add new keyboard shortcuts to the internal plist files, it was causing issues where you have custom Command Sets that don't have all the up-to-date keyboard shortcuts.

I can't remember the specifics, so we'll need to do some more testing before we remove the "reset" I think.

**Comment by randomeizer** [comment]
I guess in that case it would be good to check the existing configurations
and at least five a warning, or better, upgrade them.

**Comment by latenitefilms** [comment]
Off the top of my head, I can't really remember what the issue was... but I think Final Cut Pro has the ability to upgrade Command Sets itself (i.e. if you import a Command Set from an old version, it will still work), but it doesn't automatically update them for you if you enable FCPX Hacks, as obviously Final Cut Pro has no idea that we're messing with its plist files behind the scenes.

**Comment by randomeizer** [comment]
Yeah, I'm sure there are issues. Might be simpler if we have the ability to
'modify' the command set rather than replacing it.

**Comment by latenitefilms** [comment]
Yep - we could definitely do that. But... we really need a better plist writing module before we can tackle this. EVENTUALLY, it would be great if we could do the enable/disable Hacks shortcuts via plist manipulation, rather than the crude way we're currently doing things - which is just copying and replacing entire plist files (as opposed to modifying their contents).

**Comment by randomeizer** [comment]
Yep

**Comment by latenitefilms** [comment]
FYI: I did some tests, and Final Cut Pro doesn't seem to freak out when using a Command Set contains shortcuts that don't actually exist, so I've stopped FCPX Hacks from resetting the Command Set for now. We can re-open this issue if we start getting bug reports again.
