### ISSUE TITLE
Move FCPX Hacks Menu management to a plugin

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#217]
Relates to #136.

Create a plugin which allows other plugins to manage their own menu items.

**Comment by latenitefilms** [comment]
This sounds cool.

So you're thinking the actual menubar management will be done in a plugin (rather than the FCPX Hacks "core" - for lack of a better term)?

Ideally, each individual plugin (for example, the HUD, Voice Commands, Scrolling Timeline, etc.) will have it's menubar and shortcut "management" WITHIN the individual plugin (i.e. the default shortcuts for the HUD will be contained within the HUD plugin). Given this, maybe you need a "priority" option for the plugin loader, so that the menubar management (and eventually the shortcut management) loads first?

**Comment by randomeizer** [comment]
Yep, that's the idea. A shortcut plugin is next.

**Comment by randomeizer** [comment]
Each plugin can list dependencies, so if it needs the menu manager to load
first, it lists it as a dependency.

**Comment by latenitefilms** [comment]
Haha, yeah, I realised this as soon as I pressed "Comment". Sounds good!
