### ISSUE TITLE
Unusual amount of FCPX restarts with CommandPost 1.0.6

### ISSUE THREAD

**Issue by lguy421** [fcpxhacks/fcpxhacks#2275]
Hi Chris, 
I have been testing CommandPost for our post-production group for two weeks (really enjoying the features). However, there have been more than usual FCPX crashes (more like FCPX goes into a deadlock and I need to restart). 
Here is my log:
2/14 - 3 times restarted fcpx 
2/15 - 3 fcpx restarts/ 1 CommandPost restart (no scrolling timeline) 
2/17 - Enable Scrolling Timeline not working - needed to restart FCPX in order to get CommandPost scrolling timeline /It worked after restart
2/18 - when switching in a shared compound clip had to restart fcpx
2/19- Restarted FCPX (nothing could be clicked on). Final Cut closed when I tried to select all clips Cmd+A/ Scrolling Timeline was not working restarted FCPX but didn't help, restarting Command Post did help scrolling timeline. Three times need to Restart FCPX (nothing could be clicked on). Lost ability for playback, restarted FCPX.  Snapping is also intermittent
2/20 - Tried using the search console to bring up a grey solid, when I would hit enter it would just paste my clipboard contents. Restarted FCPX
2/24 - Restarted FCPX, Tangent Ripple would not work with FCPX. Restarted Final Cut would not let me do an undo move. 
2/25-No restarts
2/26 - Final Cut locked up so I restarted - FCPX actually did not autosave. Final Cut locked up again... But after a restart it did autosave. Got spinning wheel of death and had to restart FCPX. Had to restart again.
3/2 no restarts
We really like having the many organizational features of CommandPost, but at this point we are not able to roll the app out to our team of 17 editors here in NY due to the above test results (we also are testing for roll out to about 20 additional editors world wide). Just picking your brain to see what we can do to lessen the FCPX restarts while using CommandPost.
If this is more of an email conversation you can reach me at lguy421@gmail.com. 
Thanks, 
Luke G.
---
Working in FCPX 10.4.7
CommandPost 1.0.6
Using Tangent Ripple with Tangent Mapper version 2.3.0
Logitech G13 Advanced Gameboard
Running on Mac OS Mojave 10.14.6
iMac Pro (2017) 
3 GHz Intel Xeon W
64 GB 2666 MHz DDR4
Radeon Pro Vega 64 16 GB

**Comment by latenitefilms** [comment]
Hi Luke,

Thanks for getting in touch!

First up, there's not really any way that CommandPost can crash Final Cut Pro X. Unlike FxPlug plugins or Workflow Extensions - CommandPost is completely isolated from Final Cut Pro X, and the primarily way it communicates it is via the Accessibility API - so as far as FCPX is concerned, it doesn't really know the difference between an end user and CommandPost. As a result, you'll never reference to CommandPost in any of FCPX's crash logs.

Having said that, because CommandPost is constantly monitoring FCPX for changes, if FCPX freezes, then CommandPost will also freeze, as it's waiting for notifications. In some cases, this seems to cause a bit of a deadlock, as whilst CommandPost is waiting for FCPX, FCPX is waiting for CommandPost. As a result, if both FCPX & CP are frozen, if you force quit CP and FCPX instantly comes back to life, you can know this is a case of FCPX & CP just waiting on each other simultaneously. However if FCPX remains not responsive, then this is actually a FCPX bug.

Unless you turn off crash reporting, we use [fabric.io](fabric.io) to track CommandPost crashes, and it currently tells us at 99.8% of CommandPost users are crash-free, so CP crashing is definitely fairly uncommon across of entire user base.

Are you able to share your recent FCPX crash logs? You can find them in your user library folder (`~/Library/Logs/DiagnosticReports`).

Next time you have a problem with CommandPost not working as expected (i.e. scrolling timeline not working) are you able to submit feedback via the menubar so that we can check the CommandPost error logs? Alternatively, you can post the contents of the "Debug Console" here (you can access it by clicking **CommandPost > Open Debug Console** under the **HELP & SUPPORT** section of the CommandPost menubar).

I'd be very curious to see if you have the same amount of FCPX issues without CP running for a week, as most of the problems you've listed seem to be FCPX bugs/issues, unrelated to CommandPost.

Have you tried trashing your FCPX preferences and Custom Workspaces on this machine to see if that makes any difference to FCPX's general performance?

There's also been a few reports online that running Google Chrome at the same time as FCPX can cause all kinds of weird and wonderful issues (as they both share the same video frameworks) - are you running Chrome by any chance?

FWIW - we have CommandPost running on all our machines in the office (a mixture of MacBook Pro's & iMac 5K's) and don't have any issues day-to-day.

Is CP 1.0.6 the first version of CommandPost you've installed on your machine? If not, have you tried uninstalling CommandPost completely (using the Uninstall tool that's included in the download package)?

We'd love to help you get CommandPost running reliably across all your machines, so please let me know what else we can do to help to make this happen.

Best Regards, Chris!

**Comment by lguy421** [comment]
Man this is awesome
Thanks I’ll get to work on this tomorrow

LG

**Comment by lguy421** [comment]
Hi Chris, 

Thanks for your help! Time taken from you busy schedule is appreciated!

I will start by saying I have been testing for 3 weeks now. Two weeks have been reported above with sad results. This last week I have seen no restarts or crashes. I started with the beginning of the third week by Disabling "Enable Scrolling Timeline", and I have seen extremely good results. I know that isn't what you want to hear haha. Sad part is that's one of my favorite features ; ) Doing this has caused me not to need to trash preferences or custom workspaces. The performance has improved as of this week (will keep a look out)

Attached are two of the most recent crash logs. Github would not accept a .crash file. So I copied and pasted into a word doc. Hope that works.

[Final Cut Pro_2020-02-13-085110_USC02YD0BZHX8F_crash.docx](https://github.com/CommandPost/CommandPost/files/4298789/Final.Cut.Pro_2020-02-13-085110_USC02YD0BZHX8F_crash.docx)
[Final Cut Pro_2020-02-19-102400_USC02YD0BZHX8F_crash.docx](https://github.com/CommandPost/CommandPost/files/4298790/Final.Cut.Pro_2020-02-19-102400_USC02YD0BZHX8F_crash.docx)

I will keep in mind to submit feedback via that menubar to check CommandPost error logs.

Attached is also the Debug Console:

[CommandPost Debug Console 03062020.docx](https://github.com/CommandPost/CommandPost/files/4298812/CommandPost.Debug.Console.03062020.docx)

I am not running Chrome, I'm running Safari. 

CP 1.0.6 is the first version of CommandPost. Should I reinstall and next week test the scrolling timeline again? 

Just a moment to thank you for taking time to develop an app like this. You should win an academy award for coding. Greetings to your team from New York.

Thanks!
LG

**Comment by lguy421** [comment]
Ok Chris So I reinstalled CommandPost and turned Enable Scrolling Timeline on again. I will test it and whenever Enable Scrolling Timeline doesn't work (or any other issues) I will submit feedback. Thanks

**Comment by lguy421** [comment]
[03092020_crash log 1.docx](https://github.com/CommandPost/CommandPost/files/4308469/03092020_crash.log.1.docx)

**Comment by latenitefilms** [comment]
@lguy421 - Just checking in... are you still having issues?

FWIW - that last crash log you posted has nothing to do with CommandPost - that's a Final Cut Pro bug. If you're seeing the same crash multiple times, I'd suggest sending feedback to Apple.

**Comment by lguy421** [comment]
Hi Chris
Thanks for your help,
I have not had issues for the last two weeks.
Thanks,

LG

**Comment by latenitefilms** [comment]
Great news! I'll close this issue then. Feel free to re-open it if needed.
