### ISSUE TITLE
Add actions for Timeline Zoom

### ISSUE THREAD

**Issue by pvanleer** [fcpxhacks/fcpxhacks#2395]
{Issue still exists in .13 Beta} I'm seeing this with any action assigned to the wheel or dial. For the wheel, 10 frames back or forward is what I currently have assigned. If you do gradual turns it's fine, but as soon as you go too fast, it just quits responding, almost like it's not triggering above a certain speed of turn. For the dials, I have zoom, volume, rotation, pan left or right, and opacity assigned currently and they all behave the same as the wheel described above. 

There are no errors in the debug console because I don't think the turns are being picked up by the program to begin with once they happen. I can send video or provide more info if needed.

_Originally posted by @pvanleer in https://github.com/CommandPost/CommandPost/issues/2350#issuecomment-627757842_

**Comment by latenitefilms** [comment]
I've just tested out the "Shift Position Up/Down 1 Pixel", "Shift Position Left/Right 1 Pixel" and "Shift Rotation Left/Right by 1 Degree" actions, and they seem to be working as intended. If you turn the wheel one increment, it'll move by 1 pixel as intended. If you move fairly slowly, FCPX will keep up with the knob. If you move the knob really quickly, FCPX won't update whilst you're spinning fast, but as soon as you stop, it'll update the value to however many increments you turned (i.e. if you quickly turned 100 increments - those 100 increments will be applied as soon as you have stopped turning).

Are you able to test and see if you're still the same results?

The "Go Back 10 Frames" action however is slightly different, because all that's doing is triggering a virtual keyboard press (i.e. in the default FCPX command set, it triggers SHIFT+LEFT ARROW). Because there's a delay between turning the knob and the computer processing it - we have some protection in place that we only register a knob turn every 0.1 second, so that if you turn the knob SUPER fast (not so relevant on the Loupedeck CT, but more-so a MIDI device where you can actually turn the knob REALLY fast), you don't trigger the shortcut key a million times.

You could TRY using the "LEFT + ⇧" action instead of the "Go Back 10 Frames" action, as there might be an ever-so-slight improvement, because we just trigger the keyboard action straight away, rather than reading the active FCPX command set first, to work out what shortcut to trigger.

Does this make sense and/or solve any issues? Let me know what you think.

**Comment by pvanleer** [comment]
> I've just tested out the "Shift Position Up/Down 1 Pixel", "Shift Position Left/Right 1 Pixel" and "Shift Rotation Left/Right by 1 Degree" actions, and they seem to be working as intended. If you turn the wheel one increment, it'll move by 1 pixel as intended. If you move fairly slowly, FCPX will keep up with the knob. If you move the knob really quickly, FCPX won't update whilst you're spinning fast, but as soon as you stop, it'll update the value to however many increments you turned (i.e. if you quickly turned 100 increments - those 100 increments will be applied as soon as you have stopped turning).
> 
I just tested and am seeing this as well. The Zoom action doesn't work like described above, for example, if you turn it quickly it seems to enable some other sort of setting (pictured below).  

![Screen Shot 2020-08-13 at 9 56 55 AM](https://user-images.githubusercontent.com/54328549/90163729-55345480-dd4b-11ea-8608-3ec1911a2f2b.png)

> 
> The "Go Back 10 Frames" action however is slightly different, because all that's doing is triggering a virtual keyboard press (i.e. in the default FCPX command set, it triggers SHIFT+LEFT ARROW). Because there's a delay between turning the knob and the computer processing it - we have some protection in place that we only register a knob turn every 0.1 second, so that if you turn the knob SUPER fast (not so relevant on the Loupedeck CT, but more-so a MIDI device where you can actually turn the knob REALLY fast), you don't trigger the shortcut key a million times.
> 
> You could TRY using the "LEFT + ⇧" action instead of the "Go Back 10 Frames" action, as there might be an ever-so-slight improvement, because we just trigger the keyboard action straight away, rather than reading the active FCPX command set first, to work out what shortcut to trigger.
> 
> Does this make sense and/or solve any issues? Let me know what you think.

I recorded another video for you showing what I'm experiencing with testing what you mentioned above: https://drive.google.com/open?id=1wQ4kolj-YkcqbfsF6J7nMkwtByrZqr7k&authuser=hello%40prescottvanleer.com&usp=drive_fs

**Comment by latenitefilms** [comment]
> The Zoom action doesn't work like described above, for example, if you turn it quickly it seems to enable some other sort of setting (pictured below).

Which zoom actions are you talking about specifically?

**Comment by pvanleer** [comment]
These ones. 

![Screen Shot 2020-08-13 at 10 26 59 AM](https://user-images.githubusercontent.com/54328549/90166734-87e04c00-dd4f-11ea-81f1-2f2d76b1b030.png)

**Comment by latenitefilms** [comment]
These are just triggering keyboard shortcuts, which have the same issues/limitations as "Go Back 10 Frames" explained above.

I thought we had actions for timeline and browser zoom that open up the appearance popups so you can visually see the zoom values change - these should work better. Will check in the morning.

**Comment by pvanleer** [comment]
Any luck? With the Menu Item Zoom In and Zoom Out it seems to work properly. But for the custom Zoom In and Zoom Out actions as picture above, this is basically what shows up if I turn the Zoom dial (in or out) too quickly. Then I have to click elsewhere on the timeline again to reset it. If I turn super gradually, it works fine, but as soon as I turn too fast it triggers the tool or whatever in the photo below: 

![Screen Shot 2020-08-17 at 9 38 16 AM](https://user-images.githubusercontent.com/54328549/90420860-6348e480-e06d-11ea-8aba-1b11dde4e538.png)
