### ISSUE TITLE
Add actions for Zoom shortcut keys

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#2446]
It looks like the Zoom shortcut keys are stored in a password protected database, so I think we'll just have to hardcode in the default values. I've sent Zoom a message via Twitter DM to confirm.

**Comment by jvzuck** [comment]
[zoominit.lua.txt](https://github.com/CommandPost/CommandPost/files/5189423/zoominit.lua.txt)

Based this off the Skype init.lua file. 

I wonder if these could be data (perhaps even human readable), instead of code.
<img width="599" alt="zoomhk" src="https://user-images.githubusercontent.com/70421650/92505617-5897f000-f1d2-11ea-8755-3ec80d78a0f0.png">

**Comment by latenitefilms** [comment]
Done in #2453
