### ISSUE TITLE
New name for FCPX Hacks?

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#249]
The name "FCPX Hacks" is a bit scary for some people - as it makes it sound like we're doing all kinds of "black magic" to make things work (which we kinda are in some cases). It also limits the software's functionality to Final Cut Pro. Ideally, in the long, long, long term - I'd love to make this software more of a "toolkit" for editors, eventually adding the occasional handy feature for other programs such as Premiere, After Effects, Motion, etc.

This is definitely not something we need to do urgently, but maybe around the same time as we eventually turn FCPX Hacks into a "proper" app - we can also do a name change. Maybe this can be our 1.0 release?

I'm not sure what the right name is, but here's some (crap) ideas:

- EditKit (I was originally going to called the software "HacksKit" as a play on Apple's "Kit" terminology).
- EditHack
- Edit Toolkit
- QuickEdit
- EditTools or Editools
- EditNinja
- NinjaSuite
- Ninja Toolkit
- Ninja Toys
- EditSuite
- ProShortcuts
- EditWrangler
- EditCommand
- EditPro
- NLExtend

**Comment by randomeizer** [comment]
* FCP HaX ;)

On Sat, 21 Jan 2017 at 5:18 pm, Chris Hocking <notifications@github.com>
wrote:

The name "FCPX Hacks" is a bit scary for some people - as it makes it sound
like we're doing all kinds of "black magic" to make things work (which we
kinda are in some cases). It also limits the software's functionality to
Final Cut Pro. Ideally, in the long, long, long term - I'd love to make
this software more of a "toolkit" for editors, eventually adding the
occasional handy feature for other programs such as Premiere, After
Effects, Motion, etc.

This is definitely not something we need to do urgently, but maybe around
the same time as we eventually turn FCPX Hacks into a "proper" app - we can
also do a name change. Maybe this can be our 1.0 release?

I'm not sure what the right name is, but here's some (crap) ideas:

   - EditKit (I was originally going to called the software "HacksKit" as a
   play on Apple's "Kit" terminology).
   - EditHack
   - Edit Toolkit
   - QuickEdit
   - EditTools or Editools
   - EditNinja
   - NinjaSuite
   - Ninja Toolkit
   - Ninja Toys
   - EditSuite
   - ProShortcuts
   - EditWrangler
   - EditCommand
   - EditPro
   - NLExtend

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fcpxhacks/fcpxhacks/issues/249>, or mute the thread

**Comment by randomeizer** [comment]
Something with 'Post' in it?

**Comment by randomeizer** [comment]
Some options:

* postatomic
* postaxial
* reposted
* posterity
* posterize
* postfix
* postmaster
* postscript
* postzygapophyseal

**Comment by latenitefilms** [comment]
PostTools? Or is that too close to ProTools?

**Comment by randomeizer** [comment]
I don't mind it, but maybe a bit close.

**Comment by randomeizer** [comment]
PostNinja?

**Comment by randomeizer** [comment]
Damn: http://www.postninja.com/

However, it's not an app. It's a news aggregation site.

**Comment by latenitefilms** [comment]
PostNinja's pretty cool.

**Comment by randomeizer** [comment]
[EditButton](https://www.youtube.com/watch?v=7DD6WAr4A4Y)? ;)

**Comment by latenitefilms** [comment]
Ummm... not sold on EditButton.

Others have suggested stuff, but they all have FCPX in the name...

Sean Lander: FCPX Tools
Daniel Yates: FcpXtras
Charlie Austin: FCPXtender or FCPXtensions

I do like the Ninja component. PostNinja, EditNinja, and NinjaSuite are all pretty cool.

**Comment by randomeizer** [comment]
That was a reference to this: https://www.youtube.com/watch?v=7DD6WAr4A4Y

I think that removing FCPX from the name will potentially reduce the ire of Apple, particularly if it becomes a 'real' app.

NinjaSuite is a bit non-specific - a suite of what? PostNinja has less sylables than EditNinja, but is perhaps less clear?

**Comment by latenitefilms** [comment]
Haha, ah, right.

Yeah, I definitely want to remove Final Cut Pro from the name all together, not only to keep Apple happy, but also because I really want to make it MORE than Final Cut Pro eventually.

NinjaEdit?

**Comment by randomeizer** [comment]
'Edit' is a bit specific as well - doesn't exactly apply to After Effects/etc.

I'd prefer to have Ninja at the end, I think. Makes more sense as the noun. Edit is a verb anyway, and 'Post' is an adjective...

**Comment by latenitefilms** [comment]
It's a bit silly... FingerNinja

**Comment by randomeizer** [comment]
Heh. Feels a little...risque?

**Comment by latenitefilms** [comment]
I think PostNinja and PostKit are my favourites so far.

FilmNinja could also work?

**Comment by randomeizer** [comment]
FrameNinja?

I like PostNinja best I think. As long as we can live with the existence of the other PostNinja. They don't overlap, audience-wise.

**Comment by latenitefilms** [comment]
Judging by their Twitter page, I don't think it's been an active project for a few years anyway.

**Comment by latenitefilms** [comment]
Matt Goddard suggested "Cutlass" (a short sword with a slightly curved blade, formerly used by sailors).

**Comment by latenitefilms** [comment]
Maybe something more friendly like PostBuddy or PostAssist?

PostConsole or PostControl?

PostCmd or PostCommand?

**Comment by randomeizer** [comment]
PostOption? 😉 PostCmd kinda works, in that we provide a lot of shortcuts.
Post⌘? Or CommandPost? ⌘-Post. Hehe...

I don't mind the idea of more friendly. Maybe not quite so casual as
'buddy'. PostCentral? PostHub? PostUnity? Posterity? PostFlow?



On Tue, 24 Jan 2017 at 5:57 am, Chris Hocking <notifications@github.com>
wrote:

Maybe something more friendly like PostBuddy or PostAssist?

PostConsole or PostControl?

PostCmd or PostCommand?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/fcpxhacks/fcpxhacks/issues/249#issuecomment-274599122>,
or mute the thread

**Comment by randomeizer** [comment]
Got to say, CommandPost (or some other spelling variation) is growing on me. And there don't really seem to be any other apps or sites out there with that name, surprisingly. There is an iOS app which is a companion to a mac app called Command Bridge, but that's about it.

**Comment by latenitefilms** [comment]
CommandPost is actually really cool - I like!

My favourites are probably:

- CommandPost
- PostHub
- Cutlass
- PostNinja
- PostKit

...although I think maybe CommandPost is the best thus far.

**Comment by randomeizer** [comment]
Yeah, I think CommandPost is my favourite too, then maybe PostNinja.
Cutlass is a bit piratey, possibly a bit scary for some for similar reasons
to PostNinja, although they obviously both have potential for icons 😉

PostHub is ok, but feels more like a forum website title to me. PostKit,
maybe, but Kits in the Apple world tend to be frameworks, not applications.

**Comment by latenitefilms** [comment]
I reckon CommandPost might be the winner.
