### ISSUE TITLE
Create an installation pkg builder to simplify installation

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#28]
Currently, the code is installed by drag-n-dropping a couple of files into an Alias pointing at the `~/.hammerspoon` folder. It would be better to install via a package application.

Some useful links:
* http://errorfreeit.com.au/blog/2014/8/17/creating-os-x-package-files-pkg-in-terminal
* https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pkgbuild.1.html
*

**Comment by randomeizer** [comment]
After doing some research, I don't think this will work with the current implementation of FCPX Hacks. Packages are not designed to install files into the current user's home directory, which is exactly how this works currently.

Leaving this here (closed) for future reference.

**Comment by latenitefilms** [comment]
Long term, I think the best solution is to "fork" Hammerspoon, and release FCPX Hacks as a standalone app - but that requires me learning Objective-C, and there's also no point in seriously tackling until the Lua code is a bit more rock solid. Hopefully by that point Apple will fix all the FCPX bugs and missing features, so that FCPX Hacks becomes redundant anyway!

**Comment by randomeizer** [comment]
Yeah, was thinking about that overnight. One step at a time I guess.
