### ISSUE TITLE
Stream Deck (XL) not changing banks

### ISSUE THREAD

**Issue by cheapest-energy-windows** [fcpxhacks/fcpxhacks#3147]
Whenever assigning an action to a button on Stream Deck (XL), or within FCP (HUD) to go to the next or previous bank the information is displayed but the bank is not actually changing on the Stream Deck (XL) itself. 

Going to Control Surfuces -> Stream Deck -> Choose bank does however work. I'm only using one unit (1).

**Comment by latenitefilms** [comment]
Apologies for the delayed reply. I'll plug in a Stream Deck XL and see if I can reproduce.

**Comment by cheapest-energy-windows** [comment]
Were you able to reproduce?

**Comment by cheapest-energy-windows** [comment]
Just curious btw, I understand while quite inconvenient during editing it is not an high priority bug. :)

**Comment by KotzendesEinhorn-rgb** [comment]
I got the same problem with DaVinci Speed Editor and Avid. I would be happy for a solution...

**Comment by cheapest-energy-windows** [comment]
It looks like it might make it into the next version release, would make me extremely happy as well. As temporary workaround I've configured a button that brings me straight into the control surface configuration on each bank, that way I'm just one button away to be able to change the bank manually.

**Comment by latenitefilms** [comment]
Apologies for the delayed reply on this - I've been caught up in BRAW Toolbox and Gyroflow Toolbox, and I don't always have a **Stream Deck (XL)** at arms reach - however, I'm in the office today, so I'll plug one in and see if I can reproduce what you're seeing.

@KotzendesEinhorn-rgb - AFAIK, there's no bank issues with the DaVinci Resolve Speed Editor though.

**Comment by cheapest-energy-windows** [comment]
That is fine really, appreciate you looking into it. There might be more to it, also noticed that when executing a script from the Preference/Scripting pane works. When adding that script to a stream deck nl button it just doesn't behave the same way, like it is missing commands from the script. The P is just Reverse Clip which I configured on custom command preference in FCP.

Thanks again.

`
local fcp               = require "cp.apple.finalcutpro"
local eventtap          = require "hs.eventtap"
local keyStroke         = eventtap.keyStroke

fcp:launch()

	keyStroke({}, "P")
    keyStroke({"ctrl"}, "d")
	keyStroke({}, "-")
	keyStroke({}, "3")
	keyStroke({}, "0")
	keyStroke({}, "0")
	keyStroke({}, "return")
	keyStroke({}, "P")
    keyStroke({"ctrl"}, "d")
	keyStroke({}, "5")
	keyStroke({}, "0")
	keyStroke({}, "0")
	keyStroke({}, "return")
    keyStroke({"cmd"}, "r")
   '

**Comment by latenitefilms** [comment]
I think I've found the issue, and yes @KotzendesEinhorn-rgb, apologies - I think you're right - I think the same bug might apply to quite a few control surfaces in CommandPost. Will try push out a fix ASAP.

**Comment by latenitefilms** [comment]
I've posted a link to **v1.4.15-beta.2** in the Facebook Group if you want to test it out.

**Comment by icican** [comment]
@latenitefilms   Hello, can you send me commandpost v1.4.15-beta.2 version? My stream deck xl encountered the same problem and cannot switch banks. In CommandPost_1.4.20, banks still cannot be switched. The link you provided on facebooks is no longer valid. My email is 39504923@qq.com.
Thank you sir !

**Comment by latenitefilms** [comment]
This version has since been released publicly - so you can just use the latest public version.

**Comment by MarktheNinja** [comment]
I'm having the same issue with my Stream Deck XL. Everything works except the option to change banks. I am currently running the latest version of CommandPost v1.4.26 (Build: 8019). Any advice on how to get the bank switching to work?

**Comment by icican** [comment]
Sorry, it hasn't been resolved yet. I sent a message to the developer, but he asked me to download the latest version of the installation program. I downloaded it and it doesn't work. I have tried many methods, but I also found other methods on the Internet, but there has been no solution. If you have a solution, please also share it with me.












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CommandPost/CommandPost"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月23日(星期六) 凌晨1:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CommandPost/CommandPost] Stream Deck (XL) not changing banks (Issue #3147)





 
I'm having the same issue with my Stream Deck XL. Everything works except the option to change banks. I am currently running the latest version of CommandPost v1.4.26 (Build: 8019). Any advice on how to get the bank switching to work?

**Comment by latenitefilms** [comment]
Thanks for reporting @MarktheNinja - there's definitely something funky going on. Will investigate.

**Comment by latenitefilms** [comment]
Actually... scrap that... it does seem to be working correctly here...

Make sure you have **Preview Selected Application & Bank on Hardware** disabled (otherwise it'll just "stick" to whatever you have selected in the preferences window):

<img width="1000" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/e5d574f8-d1c8-41fc-b3d3-d6f1da9ab94b">

Make sure you're using the correct actions for changing banks:

<img width="1280" alt="image" src="https://github.com/CommandPost/CommandPost/assets/22286696/b9166486-5691-408f-8935-4792aa228f67">

**Comment by MarktheNinja** [comment]
Hey that fixed my issue! I had the Preview Selected Application & Bank on Hardware enabled.   Disabling it fixed my issue.  Thank you so much! This software is seriously the best and saves me soooo much time! And now that I have the stream deck setup with my command post workflow it should be all the more convenient! You guys are amazing! Sent from my iPhoneOn Mar 24, 2024, at 9:42 PM, Chris Hocking ***@***.***> wrote:﻿
Actually... scrap that... it does seem to be working correctly here...
Make sure you have Preview Selected Application & Bank on Hardware disabled (otherwise it'll just "stick" to whatever you have selected in the preferences window):
image.png (view on web)
Make sure you're using the correct actions for changing banks:
image.png (view on web)

**Comment by icican** [comment]
Thank you  sir!
