### ISSUE TITLE
plistParse.lua fails with complex Command Sets

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#55]
@randomeizer - Thanks for all your amazing work with transforming my crappy plist code into a proper module! Really cool!

FYI - `plistParse.lua` seems to work awesome with fairly simple plist files, however it crashes on the more complex ones, like a customised Final Cut Pro Command Set. Attached is an example. It's crashing on the `assert(ni)` code at line 119. It doesn't crash when pointing to Final Cut Pro's default Command Set.

I'll keep playing, but if you happen to know an easy fix, let me know! 

Thanks again!

[example.commandset.zip](https://github.com/fcpxhacks/fcpxhacks/files/633173/example.commandset.zip)

**Comment by randomeizer** [comment]
This turned out to be is importing a binary plist that we thought was an XML plist.

I added a `fileToTable` function which will detect which it is automatically for cars where we can't predict it.

I also fixed a bug with handling path names containing spaces, by wrapping the path in quotes after calculating the absolute path.

**Comment by latenitefilms** [comment]
Perfect, thanks mate!
