### ISSUE TITLE
Change Menubar contents depending on what is the Frontmost Application

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#650]
Currently the icon disappears during the 'Welcome' stage, and always has all items for FCPX in it (albeit disabled at times). The suggestion is that all FCPX-specific menus should only appear when FCPX is active.

Some items which are currently FCPX-specific may become more generic (Mobile notifications, Virtual Toolbar?), so we might need to put them into a different section, etc.

**Comment by latenitefilms** [comment]
> Some items which are currently FCPX-specific may become more generic (Mobile notifications, Virtual Toolbar?), so we might need to put them into a different section, etc.

I reckon we need to do things like Mobile Notifications in a similar way to how we do Preferences panel - we basically keep the "core" functionality in a core plugin, then the Final Cut Pro specific stuff in it's own Final Cut Pro plugin. For example, the Virtual Touch Bar shouldn't be app specific, however, I'd still like to keep the Final Cut Pro specific functionality in there (i.e. the ability to "lock" the Virtual Touch Bar to the top-centre of the timeline). Same deal with Mobile Notifications - although mobile notifications could be applied to any application, obviously at the moment, we only offer mobile notifications that are Final Cut Pro specific. Maybe Mobile Notifications should be moved to a Preferences panel - not sure?

**Comment by randomeizer** [comment]
Yeah, agreed. We should probably create some separate issues for those too.

**Comment by latenitefilms** [comment]
Added:

- Make Mobile Notifications a Core Plugin (Issue #658)
- Make Virtual Touch Bar a Core Plugin (Issue #657)

**Comment by latenitefilms** [comment]
This issue might be a good opportunity to move over to using/testing [`hs._asm.guitk.menubar`](https://github.com/asmagill/hammerspoon_asm/tree/master/guitk/menubar) as well - as it includes a whole bunch of menubar improvements.

**Comment by randomeizer** [comment]
This doesn't seem to be related to the menubar though. It's about the
dock.


On 31 May 2018 at 12:00 am, Chris Hocking <notifications@github.com> wrote:


This issue might be a good opportunity to move over to using/testing
hs._asm.guitk.menubar as well - as it includes a whole bunch of menubar
improvements.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/650#issuecomment-393172976>,
or mute the thread

**Comment by latenitefilms** [comment]
Huh? The original issue is basically just making the CommandPost Menubar item application context aware, right?

**Comment by randomeizer** [comment]
Yes, I guess the menu bar is involved. Not sure what the connection to
drag and drop is though :p


On 31 May 2018 at 9:08 am, Chris Hocking <notifications@github.com> wrote:


Huh? The original issue is basically just making the CommandPost Menubar
item application context aware, right?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/650#issuecomment-393348188>,
or mute the thread

**Comment by latenitefilms** [comment]
Oh right - well originally - back in the day - I wanted to do things like FCPXML sharing by dragging items from FCPX into the menu bar - but this wasn't possible using `hs.menubar` which is why I built the HUD, so that you could drag and drop things there. Eventually I was able to learn enough Objective-C to add a function to Hammerspoon that allowed you to drag & drop to the Hammerspoon dock item - so we also made use of that. Now however, with `hs._asm.guitk.menubar`, I'll be able to finally implement my original idea and allow dragging and dropping to the dock icon! That's what issue #50 is for.

This issue (#650) however is re-working the CommandPost menu bar, so that it's application context aware (i.e. if FCPX is active, the menu bar shows FCPX items - but if Motion is active, for example, it would show Motion items).

The benefit of using `hs._asm.guitk.menubar` for this is that now each menu bar item can be a callback, so that you can actually update the status of individual menu items the instant they happen (i.e. if you have the menubar open and FCPX changed a preference internally - the menubar would automatically update).

**Comment by randomeizer** [comment]
Ah, neat! How stable is the extension?


On 31 May 2018 at 9:33 am, Chris Hocking <notifications@github.com> wrote:


Oh right - well originally - back in the day - I wanted to do things like
FCPXML sharing by dragging items from FCPX into the menu bar - but this
wasn't possible using hs.menubar which is why I built the HUD, so that you
could drag and drop things there. Eventually I was able to learn enough
Objective-C to add a function to Hammerspoon that allowed you to drag &
drop to the Hammerspoon dock item - so we also made use of that. Now
however, with hs._asm.guitk.menubar, I'll be able to finally implement my
original idea and allow dragging and dropping to the dock icon! That's what
issue #50 <https://github.com/CommandPost/CommandPost/issues/50> is for.

This issue (#650 <https://github.com/CommandPost/CommandPost/issues/650>)
however is re-working the CommandPost menu bar, so that it's application
context aware (i.e. if FCPX is active, the menu bar shows FCPX items - but
if Motion is active, for example, it would show Motion items).

The benefit of using hs._asm.guitk.menubar for this is that now each menu
bar item can be a callback, so that you can actually update the status of
individual menu items the instant they happen (i.e. if you have the menubar
open and FCPX changed a preference internally - the menubar would
automatically update).

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/650#issuecomment-393352519>,
or mute the thread

**Comment by latenitefilms** [comment]
Haha... your guess is as good as mine! :)

**Comment by latenitefilms** [comment]
FYI: I did originally have this extension in the `develop` branch - but from memory I had to remove it because it was causing errors with Fabric. Will give it another bash later today.

`hs._asm.guitk.menubar` does have a legacy wrapper for `hs.menubar` too, so in theory, at least initially, we could just switch from `hs.menubar` to `hs._asm.guitk.menubar` just by changing the local definition. Will give it a go this arvo and see what breaks!
