### ISSUE TITLE
Test hs.plist and cfpreferences to see if they're faster than cp.plist

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#707]

**Comment by latenitefilms** [comment]
Possibly related: [A script for adding hotkeys to Final Cut Pro X](http://macscripter.net/viewtopic.php?pid=191191#p191191)

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as `hs._asm.cfpreferences` will probably eventually replace `hs.plist`.

See: https://github.com/asmagill/hammerspoon_asm/tree/master/cfpreferences

**Comment by randomeizer** [comment]
Let's leave this open and investigate which option works out better.

**Comment by latenitefilms** [comment]
@randomeizer - Is this what you've already done in `cp.app`?

**Comment by randomeizer** [comment]
I didn't do any testing for cfpreferences performance, and I haven't
touched hs.plist yet.


On 30 May 2018 at 11:46 pm, Chris Hocking <notifications@github.com> wrote:


@randomeizer <https://github.com/randomeizer> - Is this what you've already
done in cp.app?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/707#issuecomment-393167736>,
or mute the thread

**Comment by latenitefilms** [comment]
Given we're already using `hs._asm.cfpreferences` for `cp.app`, I'm just going to close this issue for now.
