### ISSUE TITLE
Pre-loading the Console action choices delays the 'welcome message'

### ISSUE THREAD

**Issue by randomeizer** [fcpxhacks/fcpxhacks#722]
This is due to the pre-load being done after a 3-second timer, and that slows down the hiding of the 'welcome' alert. Perhaps make it longer so that it is less noticable?

**Comment by randomeizer** [comment]
Basically, there is a time cost to running this, particularly the first time. The question is, where is the best place to hide it? At the moment it's 3 seconds after the plugin loads, but seems like this needs to be longer. Worst case is that the Console gets loaded before it pre-loads, then there is a several-second wait before the console appears the first time.

**Comment by latenitefilms** [comment]
Ummm... good question!

This isn't something that can be cached to file, or is it already cached but still takes a while to populate?

I wonder if it's worth building a "background tasks" module that uses `hs.host.idleTime()` to detect when the system isn't really doing anything, to do any non-critical tasks, like pre-loading things? We could then make it so that if the the console isn't pre-loaded, it'll just load on first usage anyway?

I think making CommandPost open quickly is probably important in terms of user perception - at least for the first time they run things. You don't really want end-users opening CommandPost for the first time, and the welcome screen gets "stuck" on the screen for a few seconds - it just looks a bit buggy.

You could also potentially "hide it" during the Final Cut Pro loading process, as Final Cut Pro takes a few seconds to load anyway?

**Comment by randomeizer** [comment]
Not simple to cache, because the values available can change at any time (for example, if you change langauges).

**Comment by latenitefilms** [comment]
Now that the Final Cut Pro scanning code scans every language - and so can your fancy new menu code, should we just cache all the languages?

**Comment by randomeizer** [comment]
No

**Comment by randomeizer** [comment]
:P

**Comment by randomeizer** [comment]
It's actually the menus that eat up most of the time. And they are always changing...

**Comment by latenitefilms** [comment]
No worries. Could we cache everything BUT the menu? Or will that not really save any time?

**Comment by randomeizer** [comment]
If we can build something around idle time, that could be good.

With regards to caching, what items in that list can you guarantee won't change?

**Comment by latenitefilms** [comment]
Well, I guess none of the effects will change, UNLESS the user triggers a "Scan Final Cut Pro" action - in which case, we could refresh the cache for this as part of the scanning process?

Really though, I trust whatever you think's best - as all this code has gotten so crazy complex and advanced now, that I've completely lost track of what's currently cached and what's not at the moment.

**Comment by randomeizer** [comment]
The effects will change whenever a user modifies a template, installs new effects, etc. Probably not changing that often really.

Commands won't change outside of reloads of CP, so they could be cached, theoretically.

Menus are the trickiest, since they are constantly changing. Currently we're only refreshing it if FCPX reloads though.

**Comment by randomeizer** [comment]
FYI, the Scan Final Cut Pro button doesn't actually do anything functional, other than comparing the list in the GUI to what is generated programatically.

**Comment by latenitefilms** [comment]
Oh right, I didn't realise that - that's awesome! So I assume you've already removed the "Scan Final Cut Pro" welcome screen. Should we just remove the button now in Preferences as well? We can always just trigger the comparison code from the Error Log?

**Comment by randomeizer** [comment]
We could remove it. The main reason I haven't is because I thought it might
be a useful debugging tool on users machines. However, it would be more
useful if it would email us the results automatically.

**Comment by latenitefilms** [comment]
Maybe we move it to the "Help & Support" section of the menubar (i.e. take it out of the Preferences panel), and make it trigger the feedback form after running?
