### ISSUE TITLE
Console/Activator/Chooser Loading Bug

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#787]
I've noticed that if the Console hasn't already pre-loaded it's choices, it's possible to show the Console/Activator BEFORE the callbacks have been set up, so it won't work as expected. You need to close the Console then option it again for it to work properly.

This is reproducible if you very quickly try to open a Console after reloading CommandPost before the pre-loaders have done their thing.

**Comment by randomeizer** [comment]
I'm not quite sure how this is happening. I can replicate it sometimes, but (for example), when you click a menu item in the right-click submenu, such as turning off 'Menu Item' values, it won't update until you close and reopen the Console. But the functions are working correctly, in that the box gets unchecked. It's just the chooser which is not working correctly.

As such, I think this might be a bug in hs.chooser, but not exactly sure how to pin it down.

**Comment by latenitefilms** [comment]
Is there a way to add in a check to make sure all the callbacks and support functions have finished BEFORE showing the `hs.chooser`?

**Comment by latenitefilms** [comment]
I think the problem is that the callback functions are taking longer to process than it takes to display the chooser?

**Comment by randomeizer** [comment]
Timing of when things appear/hide/etc are a bit variable. For example, the reason that the "CommandPost 1.0.0-XXX has loaded" popup stays open for a while sometimes is because it uses a timer to close it again, and if something else happens before the timer runs that takes a while (eg, updating the Console options), it has to wait until that is done until the 'close' action will happen.

With regards to this issue, I'm just guessing, but it seems like some internal part of hs.chooser isn't quite wired up when the list takes a while to load. So, when we what the list content should look like via the right-click menu, it doesn't update any more. Not sure what we can do from here really.

**Comment by latenitefilms** [comment]
I wonder if it's a matter of caching all the chooser values BEFORE creating the `hs.chooser`? If it's just receiving a value that's already been formulated and cached, then it shouldn't have to wait for anything?

**Comment by latenitefilms** [comment]
Could we prevent the CommandPost menubar item from appearing until all the Activator's are setup and ready to go?
