### ISSUE TITLE
Plugins that restart Final Cut Pro should use doRestart

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#805]
Currently when you reload Final Cut Pro via `cp.apple.finalcutpro` it halts CommandPost until Final Cut Pro has restarted (i.e. it's blocking). This should not be the case, as we should just use callbacks to determine when FCPX has finished restarting.

**Comment by cailyoung** [comment]
http://www.lua.org/manual/5.3/manual.html#6.2

coroutine might help here?

**Comment by randomeizer** [comment]
This would be a good candidate for RxLua.

Regards,

David


On 7 Jun 2018 at 10:13 pm, Chris Hocking <notifications@github.com> wrote:


Assigned #805 <https://github.com/CommandPost/CommandPost/issues/805> to
@randomeizer <https://github.com/randomeizer>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/805#event-1668400777>,
or mute the thread

**Comment by latenitefilms** [comment]
Have you already solved this @randomeizer ?

**Comment by randomeizer** [comment]
There is a callback version (`doRestart()`), but I think that most places are still using the blocking version currently.
