### ISSUE TITLE
Disable Final Cut Pro Commands when Open/Save Dialog is Frontmost

### ISSUE THREAD

**Issue by latenitefilms** [fcpxhacks/fcpxhacks#994]

**Comment by latenitefilms** [comment]
This should be fairly easy to implement?

**Comment by randomeizer** [comment]
This should be something triggered by watching fcp.isModalDialogOpen


On 30 May 2018 at 11:52 pm, Chris Hocking <notifications@github.com> wrote:


This should be fairly easy to implement?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CommandPost/CommandPost/issues/994#issuecomment-393170066>,
or mute the thread

**Comment by latenitefilms** [comment]
I'll have a play with this later today.

**Comment by latenitefilms** [comment]
@randomeizer - Ummm... looks like you've already tried to implement this, but it doesn't work?

```lua
    --------------------------------------------------------------------------------
    -- Enable/Disable as Final Cut Pro becomes Active/Inactive:
    --------------------------------------------------------------------------------
    mod.isEnabled = fcp.isFrontmost:AND(fcp.isModalDialogOpen:NOT()):watch(function(enabled)
        mod.cmds:isEnabled(enabled)
    end)
```
